# Generated by Django 6.0.6 on 2026-07-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='type',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
